#! /bin/sh
# Check Autoconf version
v250=`which autoconf2.50 2> /dev/null`
if [ -x "$v250" ]; then
	rm -f configure.in
else
	if [ -x `which autoconf` ]; then
		AC_VER=`autoconf --version | head -1 | sed 's/^[^0-9]*//i'`
		AC_VER_MAJOR=`echo $AC_VER | cut -f1 -d'.'`
		AC_VER_MINOR=`echo $AC_VER | cut -f2 -d'.'`

		if [ "$AC_VER_MAJOR" -lt "2" ]; then
			echo "Autoconf 2.13 or greater needed to build configure."
			exit 1
		fi

		if [ "$AC_VER_MINOR" -lt "13" ]; then
			echo "Autoconf 2.13 or greater needed to build configure."
			exit 1
		fi

		if [ "$AC_VER_MINOR" -lt "50" ]; then
			if [ ! -e configure.in ]; then
				ln -s configure.ac configure.in
			fi
			echo "If you see some warnings about cross-compiling, don't worry; this is normal."
		else
			rm -f configure.in
		fi
	else
		echo Autoconf not found. QuakeForge CVS requires autoconf to bootstrap itself.
		exit 1
	fi
fi

aclocal && autoheader && libtoolize --automake && automake --add-missing && autoconf
