#define GIB_E_EXIT	-2
#define GIB_E_RETURN	-1
#define GIB_E_PARSE	1
#define GIB_E_NUMARGS	2
#define GIB_E_ARG	3
#define GIB_E_CALLS	4
#define GIB_E_NOSUB	5
#define GIB_E_NOVAR	6
#define GIB_E_BUFFER	7
#define GIB_E_TYPE	8
#define GIB_E_ULIMIT	9
#define GIB_E_ILLINST	10
