float(string s) cvar = #45;		// return cvar.value
void(string var, string val) cvar_set = #72;    // sets cvar.value
string(float f) ftos = #26;		// converts float to string
integer(float f) ftoi = #110;		// converts float to integer
string(integer i) itos = #112;		// converts interger to string
integer(string str) stoi = #113;		// converts string to integer
float(string str) stof = #81;		// converts string to float
void(string s) dprint                           = #25;
