#!/bin/sh -e

update-alternatives --install /usr/share/games/quake/QFplugins/snd_output_default.so quakeforge-audio-default /usr/share/games/quake/QFplugins/snd_output_disk.so 10
update-alternatives --install /usr/share/games/quake/QFplugins/snd_output_default.so quakeforge-audio-default /usr/share/games/quake/QFplugins/snd_output_null.so 20

if [ "$1" = "configure" ]; then
  ldconfig
fi

#DEBHELPER#

exit 0
