#ifndef VEC_TYPE
#define VEC_TYPE(type_name, base_type)
#endif

VEC_TYPE(ivec2, int)
VEC_TYPE(ivec3, int)
VEC_TYPE(ivec4, int)
VEC_TYPE(vec2, float)
VEC_TYPE(vec3, float)
VEC_TYPE(vec4, float)
VEC_TYPE(lvec2, long)
VEC_TYPE(lvec3, long)
VEC_TYPE(lvec4, long)
VEC_TYPE(dvec2, double)
VEC_TYPE(dvec3, double)
VEC_TYPE(dvec4, double)
VEC_TYPE(uvec2, uint)
VEC_TYPE(uvec3, uint)
VEC_TYPE(uvec4, uint)
VEC_TYPE(ulvec2, ulong)
VEC_TYPE(ulvec3, ulong)
VEC_TYPE(ulvec4, ulong)
VEC_TYPE(sbvec2, sbyte)
VEC_TYPE(sbvec3, sbyte)
VEC_TYPE(sbvec4, sbyte)
VEC_TYPE(ubvec2, ubyte)
VEC_TYPE(ubvec3, ubyte)
VEC_TYPE(ubvec4, ubyte)
VEC_TYPE(svec2, short)
VEC_TYPE(svec3, short)
VEC_TYPE(svec4, short)
VEC_TYPE(usvec2, ushort)
VEC_TYPE(usvec3, ushort)
VEC_TYPE(usvec4, ushort)
VEC_TYPE(hvec2, half)
VEC_TYPE(hvec3, half)
VEC_TYPE(hvec4, half)

#undef VEC_TYPE
