#include <math.h>

vector v_forward, v_up, v_right;

float () random = #7;
int (float f) ftoi = #0x000f0000 + 110;
float (int i) itof = #0x000f0000 + 111;
vector (vector v) normalize = #9;
float (vector v) vlen = #12;
float (vector v) vectoyaw = #13;
float (float v) rint = #36;
float (float v) floor = #37;
float (float v) ceil = #38;
float (float f) fabs = #43;
vector (vector v) vectoangles = #51;

float (float x) sin = #0;
float (float x) cos = #0;
float (float x) tan = #0;
float (float x) asin = #0;
float (float x) acos = #0;
float (float x) atan = #0;
float (float y, float x) atan2 = #0;
float (float x) exp = #0;
float (float x) log = #0;
float (float x) log2 = #0;
float (float x) log10 = #0;
float (float x, float y) pow = #0;
float (float x) sinh = #0;
float (float x) cosh = #0;
float (float x) tanh = #0;
float (float x) asinh = #0;
float (float x) acosh = #0;
float (float x) atanh = #0;
float (float x) sqrt = #0;
float (float x) cbrt = #0;
float (float x, float y) hypot = #0;

double (double v) floor = #0;
double (double v) ceil = #0;
double (double f) fabs = #0;
double (double x) sin = #0;
double (double x) cos = #0;
double (double x) tan = #0;
double (double x) asin = #0;
double (double x) acos = #0;
double (double x) atan = #0;
double (double y, double x) atan2 = #0;
double (double x) exp = #0;
double (double x) log = #0;
double (double x) log2 = #0;
double (double x) log10 = #0;
double (double x, double y) pow = #0;
double (double x) sinh = #0;
double (double x) cosh = #0;
double (double x) tanh = #0;
double (double x) asinh = #0;
double (double x) acosh = #0;
double (double x) atanh = #0;
double (double x) sqrt = #0;
double (double x) cbrt = #0;
double (double x, double y) hypot = #0;
