include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME=		MainPrefs
BUNDLE_EXTENSION=	.forgeb
BUNDLE_INSTALL_DIR=	$(GNUSTEP_LOCAL_ROOT)/Library/Forge

MainPrefs_OBJC_FILES=	\
	MainPrefsView.m \
	MainPrefs.m

MainPrefs_HEADERS= \
	MainPrefsView.h \
	MainPrefs.h

MainPrefs_PRINCIPAL_CLASS= \
	MainPrefs

#MainPrefs_RESOURCE_FILES= \
#	Forge.tiff

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/bundle.make

-include GNUmakefile.postamble
